CREATE TABLE Account (
	AccountId INT NOT NULL,
    AccountUser VARCHAR(100),
    [Password] VARCHAR(256),
    IsActive BIT DEFAULT (1) NOT NULL,
    CONSTRAINT PK_Account PRIMARY KEY (AccountId)
);

CREATE TABLE Rol (
	RolId INT NOT NULL,
    Name VARCHAR(120),
    Description VARCHAR(256),
    CONSTRAINT PK_Rol PRIMARY KEY (RolId)
);

CREATE TABLE RolAccount(
	AccountId INT NOT NULL, 
	RolId INT NOT NULL,
	CONSTRAINT PK_RolAccount PRIMARY KEY(AccountId, RolId),
	FOREIGN KEY (AccountId) REFERENCES Account (AccountId) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (RolId) REFERENCES Rol (RolId) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE [Option] (
	OptionId INT NOT NULL, 
	Name VARCHAR(120),
	CONSTRAINT PK_Option PRIMARY KEY (OptionId)
);

CREATE TABLE ActionType(
	ActionTypeId INT NOT NULL, 
	Name VARCHAR(50),
	CONSTRAINT PK_ActionTypeId PRIMARY KEY(ActionTypeId)
);

CREATE TABLE [Action] (
	ActionId INT NOT NULL, 
	OptionId INT NOT NULL,
	ActionTypeId INT NOT NULL,
	CONSTRAINT PK_Action PRIMARY KEY(ActionId),
	FOREIGN KEY (OptionId) REFERENCES [Option] (OptionId) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (ActionTypeId) REFERENCES ActionType (ActionTypeId) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE RolOption (
	OptionId INT NOT NULL, 
	RolId INT NOT NULL,
	CONSTRAINT PK_RolOption PRIMARY KEY(OptionId, RolId),
	FOREIGN KEY (OptionId) REFERENCES [Option] (OptionId) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (RolId) REFERENCES Rol (RolId) ON DELETE NO ACTION ON UPDATE NO ACTION	
);

ALTER TABLE Costumer ADD AccountId INT NOT NULL